/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HERMANOS
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.setTitle("Ejercicio 2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiNombre = new javax.swing.JLabel();
        btnEsquina = new javax.swing.JButton();
        btnCentro = new javax.swing.JButton();
        btnAgrandar = new javax.swing.JButton();
        btnAchicar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiNombre.setBackground(new java.awt.Color(0, 0, 255));
        etiNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiNombre.setText("EFRAIN MAY");
        etiNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));

        btnEsquina.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEsquina.setText("Esquina");
        btnEsquina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEsquinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEsquinaMouseExited(evt);
            }
        });
        btnEsquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsquinaActionPerformed(evt);
            }
        });

        btnCentro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCentro.setText("Centro");
        btnCentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCentroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCentroMouseExited(evt);
            }
        });
        btnCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentroActionPerformed(evt);
            }
        });

        btnAgrandar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgrandar.setText("Agrandar");
        btnAgrandar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgrandarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgrandarMouseExited(evt);
            }
        });
        btnAgrandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrandarActionPerformed(evt);
            }
        });

        btnAchicar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAchicar.setText("Achicar");
        btnAchicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAchicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAchicarMouseExited(evt);
            }
        });
        btnAchicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAchicarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Efrain May Mayo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgrandar)
                            .addComponent(btnEsquina, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAchicar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(etiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(etiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEsquina)
                    .addComponent(btnCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgrandar)
                    .addComponent(btnAchicar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsquinaActionPerformed
        // TODO add your handling code here:
        etiNombre.setSize(100,120);
        etiNombre.setLocation(WIDTH, WIDTH);
        System.out.println("Acabas de presionar el boton Esquina");
    }//GEN-LAST:event_btnEsquinaActionPerformed

    private void btnCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentroActionPerformed
        etiNombre.setSize(100,90);
        etiNombre.setLocation(250,150);
        System.out.println("Acabas de presionar el boton Centro");
    }//GEN-LAST:event_btnCentroActionPerformed

    private void btnEsquinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEsquinaMouseEntered
        System.out.println("Acabas de pasar el raton por el boton de la esquina");
    }//GEN-LAST:event_btnEsquinaMouseEntered

    private void btnAgrandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrandarActionPerformed
        etiNombre.setSize(200,90);
        etiNombre.setLocation(150,150);
        System.out.println("Acabas de presionar el boton Agrandar");
    }//GEN-LAST:event_btnAgrandarActionPerformed

    private void btnAchicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAchicarActionPerformed
        etiNombre.setSize(50,90);
        etiNombre.setLocation(300,200);
        System.out.println("Acabas de presionar el boton Achicar");
    }//GEN-LAST:event_btnAchicarActionPerformed

    private void btnAgrandarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgrandarMouseEntered
        System.out.println("Acabas de pasar el raton por el boton agrandar");
    }//GEN-LAST:event_btnAgrandarMouseEntered

    private void btnCentroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentroMouseEntered
        System.out.println("Acabas de pasar el raton por el boton centro");
    }//GEN-LAST:event_btnCentroMouseEntered

    private void btnAchicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAchicarMouseEntered
        System.out.println("Acabas de pasar el raton por el boton achicar");
    }//GEN-LAST:event_btnAchicarMouseEntered

    private void btnEsquinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEsquinaMouseExited
        System.out.println("Acabas de salir");
    }//GEN-LAST:event_btnEsquinaMouseExited

    private void btnAgrandarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgrandarMouseExited
        System.out.println("Acabas de salir");
    }//GEN-LAST:event_btnAgrandarMouseExited

    private void btnCentroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentroMouseExited
        System.out.println("Acabas de salir");
    }//GEN-LAST:event_btnCentroMouseExited

    private void btnAchicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAchicarMouseExited
        System.out.println("Acabas de salir");
    }//GEN-LAST:event_btnAchicarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAchicar;
    private javax.swing.JButton btnAgrandar;
    private javax.swing.JButton btnCentro;
    private javax.swing.JButton btnEsquina;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void btnEsquinaActionPerformed() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
